In [1]:
# 라이브러리 사용 

import tensorflow as tf 
import pandas as pd

In [2]:
# 1. 과거의 데이터 준비 

파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

# 종속변수가 범주형 = 분류모델 / 양적 = 회귀모델 

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [4]:
# 원핫인코딩

아이리스 = pd.get_dummies(아이리스)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [5]:
# 종속변수, 독립변수 

독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [6]:
# 2. 모델 구조 만들기 

X = tf.keras.layers.Input(shape = [4])
Y = tf.keras.layers.Dense(3, activation = 'softmax')(X)

# softmax과 sigmoid 비교해 보기! 

model = tf.keras.models.Model(X, Y)
model.compile(loss = 'categorical_crossentropy',
              metrics = 'accuracy') # 정확도 표시, 1에 가까울수록 정확도가 높음

In [7]:
# 3. 데이터 모델 학습(FIT)

model.fit(독립, 종속, epochs = 1000, verbose = 0)
model.fit(독립, 종속, epochs = 10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1596 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1590 - accuracy: 0.9733
Epoch 3/10
5/5 [==============================] - 0s 4ms/step - loss: 0.1592 - accuracy: 0.9733
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1591 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1586 - accuracy: 0.9733
Epoch 6/10
5/5 [==============================] - 0s 4ms/step - loss: 0.1586 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1585 - accuracy: 0.9733
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1581 - accuracy: 0.9733
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1591 - accuracy: 0.9733
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1580 - accuracy: 0.9733


In [8]:
# 모델 이용하기 
# 맨 처음 데이터 5개

print(model.predict(독립[:5]))
print(종속[:5])

[[9.9905521e-01 9.4464910e-04 6.2945851e-08]
 [9.9557257e-01 4.4267098e-03 6.9390757e-07]
 [9.9827635e-01 1.7234272e-03 2.1820445e-07]
 [9.9581474e-01 4.1843439e-03 9.4189528e-07]
 [9.9931812e-01 6.8184786e-04 4.4458815e-08]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [9]:
# 맨 마지막 데이터 5개

print(model.predict(독립[-5:]))
print(종속[-5:])

[[1.0367966e-06 1.4722484e-01 8.5277414e-01]
 [1.7544154e-06 2.0627220e-01 7.9372603e-01]
 [4.1383632e-06 2.4660896e-01 7.5338691e-01]
 [1.5705822e-06 1.0748122e-01 8.9251727e-01]
 [1.1264236e-05 2.6539943e-01 7.3458922e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [10]:
# weights & bias 출력 (학습한 가중치)

print(model.get_weights())

[array([[ 0.71523327,  0.8341817 , -0.23287824],
       [ 2.8700347 , -0.273723  , -1.5578308 ],
       [-3.8556242 , -0.920515  ,  0.78103083],
       [-3.9991612 , -1.1840559 ,  1.659847  ]], dtype=float32), array([ 2.1396694,  0.9002587, -1.730597 ], dtype=float32)]
