In [1]:
# 라이브러리 사용 

import tensorflow as tf
import pandas as pd

# 보스턴 집값 예측

In [2]:
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)

In [3]:
# 종속변수, 독립변수
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [6]:
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation = 'swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [7]:
# 모델 구조 확인
model.summary()

# Param은 컴퓨터가 사용하는 가중치의 개수 
# 위 독립변수의 개수 + 1 * H레이어의 개수 
# (13 + 1) * 10 = 140

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                140       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [10]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose = 0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 16.2741
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 16.2524
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 15.9251
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 15.9784
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 17.7675
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 15.8350
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 16.4725
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 16.1440
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 16.9430
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 16.7211


In [11]:
# 4. 모델을 이용합니다
print(model.predict(독립[:5]))
print(종속[:5])

[[31.460258]
 [21.99565 ]
 [31.808153]
 [31.213251]
 [28.021427]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [12]:
# 모델의 수식 확인
print(model.get_weights())

[array([[ 0.14460818,  0.05802052,  0.38214803, -0.17139032,  0.69903135,
         0.24810292, -0.41697562,  0.37658632, -0.00988845, -0.0443978 ],
       [-0.30035755, -0.04381096,  0.01847857,  0.15818135, -0.2202334 ,
        -0.15896139, -0.07568281,  0.12657505,  0.10410906, -0.01756292],
       [ 0.22102395,  0.05674283,  0.08339194, -0.0346525 , -0.2920418 ,
         0.15185298,  0.1511046 , -0.07108708,  0.6604508 , -0.18034266],
       [-0.05741307,  2.0065463 , -0.11330598,  0.2676519 , -0.32789427,
         0.7246723 , -0.98393995,  0.10843002,  1.2614769 , -0.13017647],
       [-0.02892066, -0.6584902 ,  0.3800306 ,  0.05843817,  0.99938285,
         0.21654274, -0.423144  ,  0.1312028 , -0.8835439 ,  0.38488644],
       [-1.6845931 ,  2.0508137 , -2.2384248 ,  2.5286663 ,  2.9702787 ,
         2.4208295 , -0.28295624,  2.2327945 , -2.14723   ,  2.2795267 ],
       [ 0.27575272,  0.05122704, -0.36059296,  0.24826883, -0.47517255,
         0.09205312, -0.38055858, -0.5172154

# 아이리스 품종 분류

In [13]:
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

In [14]:
# 원핫인코딩
아이리스 = pd.get_dummies(아이리스)

In [15]:
# 종속변수, 독립변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [18]:
# 2-1. 모델의 구조를 만듭니다(히든 레이어 없음)
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [19]:
# 모델 구조 확인
model.summary()

Model: "model_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_8 (Dense)              (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [20]:
# 2-2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation = 'swish')(X)
H = tf.keras.layers.Dense(8, activation = 'swish')(H)
H = tf.keras.layers.Dense(8, activation = 'swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [21]:
# 모델 구조 확인
model.summary()

Model: "model_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_9 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_10 (Dense)             (None, 8)                 72        
_________________________________________________________________
dense_11 (Dense)             (None, 8)                 72        
_________________________________________________________________
dense_12 (Dense)             (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [22]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose = 0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0456 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0502 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0493 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0491 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0469 - accuracy: 0.9867
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0441 - accuracy: 0.9867
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0426 - accuracy: 0.9867
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0475 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0507 - accuracy: 0.9867
Epoch 10/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0526 - accuracy: 0.9800


In [23]:
# 4. 모델을 이용합니다
print(model.predict(독립[:5]))
print(종속[:5])

[[1.0000000e+00 1.0703683e-26 1.2814209e-17]
 [1.0000000e+00 5.3875661e-22 1.9527220e-14]
 [1.0000000e+00 8.1772178e-24 8.8508273e-16]
 [1.0000000e+00 1.0015207e-20 1.2213700e-13]
 [1.0000000e+00 4.6546653e-27 6.6393834e-18]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
