In [1]:
# Load scikit-learn's datasets
from sklearn import datasets

# Load digis dataset
digits = datasets.load_digits()

In [3]:
# 특성 행렬 생성
features = digits.data
features

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [5]:
# 타겟 벡터 생성 
target = digits.target
target

array([0, 1, 2, ..., 8, 9, 8])

In [6]:
# View first observation 
features[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [7]:
# 선형회귀에 많이 사용되는 데이터셋 불러오기 
from sklearn.datasets import make_regression

In [9]:
# 특성 행렬, 타겟 벡터, 정답 계수를 생성 
features, target, coefficients = make_regression(n_samples = 100, 
                                                 n_features = 3,
                                                 n_informative = 3, 
                                                 n_targets = 1, 
                                                 noise = 0.0, 
                                                 coef = True, 
                                                 random_state = 1)
# 특성 행렬, 타겟 벡터 확인 
print('Feature Matrix\n', features[:3])
print('Target Vector\n', target[:3])

Feature Matrix
 [[ 1.29322588 -0.61736206 -0.11044703]
 [-2.793085    0.36633201  1.93752881]
 [ 0.80186103 -0.18656977  0.0465673 ]]
Target Vector
 [-10.37865986  25.5124503   19.67705609]


In [10]:
# 분류에 많이 사용되는 데이터셋 불러오기 
from sklearn.datasets import make_classification

In [11]:
# 군집에 많이 사용되는 데이터셋 불러오기 
from sklearn.datasets import make_blobs

In [12]:
# 판다스로 불러오기 url의 csv 가져오기 
import pandas as pd

url = 'http://tinyurl.com/simulated_data'

dataframe = pd.read_csv(url) # 위 url이 위치한 자리에 데이터셋이 없는 모양... 

dataframe.head(2)

HTTPError: HTTP Error 404: Not Found

In [21]:
# 실습 
import pandas as pd

dataframe = pd.read_csv('C:\Users\82109\Desktop/GVOline_equipment.csv')
dataframe.head()

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-21-37877104d70e>, line 4)

In [22]:
import pandas as pd 

dataframe = pd.DataFrame()

dataframe['Name'] = ['Jacky Jackson', 'Steven Stevenson']
dataframe['Age'] = [38, 25]
dataframe['Driver'] = [True, False]

In [23]:
dataframe

Name  Age  Driver
0     Jacky Jackson   38    True
1  Steven Stevenson   25   False

In [24]:
# 행 추가 
new_person = pd.Series(['Molly Mooney', 40, True], index = ['Name', 'Age', 'Driver'])

In [25]:
new_person

Name      Molly Mooney
Age                 40
Driver            True
dtype: object

In [35]:
# 추가된 데이터 데이터셋에 추가 하기 
dataframe.append(new_person, ignore_index=True)

Name  Age  Driver
0     Jacky Jackson   38    True
1  Steven Stevenson   25   False
2      Molly Mooney   40    True

In [36]:
# 데이터셋의 모양(행, 열)
dataframe.shape

(2, 3)

In [28]:
# 숫자데이터의 구조/통계
dataframe.describe()

Age
count   2.000000
mean   31.500000
std     9.192388
min    25.000000
25%    28.250000
50%    31.500000
75%    34.750000
max    38.000000

In [29]:
# 행 검색 
dataframe.iloc[0]


Name      Jacky Jackson
Age                  38
Driver             True
Name: 0, dtype: object

In [32]:
dataframe.iloc[1:4]

Name  Age  Driver
1  Steven Stevenson   25   False

In [37]:
dataframe

Name  Age  Driver
0     Jacky Jackson   38    True
1  Steven Stevenson   25   False

In [48]:
# 타이타닉 데이터셋을 찾아서 dataframe으로 불러오기 

import pandas as pd 

dataframe = pd.read_excel('titanic.xls')

In [49]:
dataframe.head()

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

In [51]:
# 여성만 출력
dataframe[dataframe['sex'] == 'female'].head(2)

pclass  survived                           name     sex   age  sibsp  \
0       1         1  Allen, Miss. Elisabeth Walton  female  29.0      0   
2       1         0   Allison, Miss. Helen Loraine  female   2.0      1   

   parch  ticket      fare    cabin embarked boat  body  \
0      0   24160  211.3375       B5        S    2   NaN   
2      2  113781  151.5500  C22 C26        S  NaN   NaN   

                         home.dest  
0                     St Louis, MO  
2  Montreal, PQ / Chesterville, ON

In [55]:
# 여성 중 65세 이상을 출력
dataframe[(dataframe['sex'] == 'female') & (dataframe['age'] >= 65)]

pclass  survived                                               name  \
61       1         1  Cavendish, Mrs. Tyrell William (Julia Florence...   

       sex   age  sibsp  parch ticket   fare cabin embarked boat  body  \
61  female  76.0      1      0  19877  78.85   C46        S    6   NaN   

                  home.dest  
61  Little Onn Hall, Staffs

In [57]:
# 성별에서 female을 woman으로 바꾸기 
dataframe['sex'].replace('female', 'woman')

0       woman
1        male
2       woman
3        male
4       woman
        ...  
1304    woman
1305    woman
1306     male
1307     male
1308     male
Name: sex, Length: 1309, dtype: object

In [58]:
# 동시에 여러 개 바꾸기 
dataframe['sex'].replace(['female', 'male'], ['woman', 'man'])

0       woman
1         man
2       woman
3         man
4       woman
        ...  
1304    woman
1305    woman
1306      man
1307      man
1308      man
Name: sex, Length: 1309, dtype: object

In [61]:
# 열 이름 바꾸기 
dataframe.rename(columns = {'pclass': 'Passenger Class'}).head(2)

Passenger Class  survived                            name     sex      age  \
0                1         1   Allen, Miss. Elisabeth Walton  female  29.0000   
1                1         1  Allison, Master. Hudson Trevor    male   0.9167   

   sibsp  parch  ticket      fare    cabin embarked boat  body  \
0      0      0   24160  211.3375       B5        S    2   NaN   
1      1      2  113781  151.5500  C22 C26        S   11   NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON

In [63]:
# 여러 개의 열 이름 한 번에 바꾸기 
dataframe.rename(columns = {'pclass': 'passenger class', 'sex':'gender'}).head(2)

passenger class  survived                            name  gender      age  \
0                1         1   Allen, Miss. Elisabeth Walton  female  29.0000   
1                1         1  Allison, Master. Hudson Trevor    male   0.9167   

   sibsp  parch  ticket      fare    cabin embarked boat  body  \
0      0      0   24160  211.3375       B5        S    2   NaN   
1      1      2  113781  151.5500  C22 C26        S   11   NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON

In [64]:
# 열 이름 재정의하기 

import collections

column_names = collections.defaultdict(str)

column_names

defaultdict(str, {})

In [65]:
for name in dataframe.columns:
    column_names[name]
    
column_names

defaultdict(str,
            {'pclass': '',
             'survived': '',
             'name': '',
             'sex': '',
             'age': '',
             'sibsp': '',
             'parch': '',
             'ticket': '',
             'fare': '',
             'cabin': '',
             'embarked': '',
             'boat': '',
             'body': '',
             'home.dest': ''})

In [66]:
# 통계 
print('Maximum', dataframe['age'].max())
print('Minimum', dataframe['age'].min())
print('Mean', dataframe['age'].mean())
print('Sum', dataframe['age'].sum())
print('Count', dataframe['age'].count())

Maximum 80.0
Minimum 0.1667
Mean 29.8811345124283
Sum 31255.6667
Count 1046


In [67]:
dataframe.count()

pclass       1309
survived     1309
name         1309
sex          1309
age          1046
sibsp        1309
parch        1309
ticket       1309
fare         1308
cabin         295
embarked     1307
boat          486
body          121
home.dest     745
dtype: int64

In [72]:
# 고유값 찾기 
dataframe['sex'].unique()


array(['female', 'male'], dtype=object)

In [69]:
# 고유한 값 각각의 개수
dataframe['sex'].value_counts()

male      843
female    466
Name: sex, dtype: int64

In [73]:
# 고유한 값의 개수를 출력
dataframe['pclass'].nunique()

3

In [76]:
# 결측치 찾기 
dataframe[dataframe['age'].isnull()]

pclass  survived                                               name  \
15         1         0                                Baumann, Mr. John D   
37         1         1      Bradley, Mr. George ("George Arthur Brayton")   
40         1         0                          Brewe, Dr. Arthur Jackson   
46         1         0                              Cairns, Mr. Alexander   
59         1         1  Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genev...   
...      ...       ...                                                ...   
1293       3         0                  Williams, Mr. Howard Hugh "Harry"   
1297       3         0                             Wiseman, Mr. Phillippe   
1302       3         0                                  Yousif, Mr. Wazli   
1303       3         0                              Yousseff, Mr. Gerious   
1305       3         0                              Zabour, Miss. Thamine   

         sex  age  sibsp  parch      ticket     fare cabin embarked boat  \
15      male  NaN      0      0    PC 17318  25.9250   NaN        S  NaN   
37      male  NaN      0      0      111427  26.5500   NaN        S    9   
40      male  NaN      0      0      112379  39.6000   NaN        C  NaN   
46      male  NaN      0      0      113798  31.0000   NaN        S  NaN   
59    female  NaN      0      0       17770  27.7208   NaN        C    5   
...      ...  ...    ...    ...         ...      ...   ...      ...  ...   
1293    male  NaN      0      0    A/5 2466   8.0500   NaN        S  NaN   
1297    male  NaN      0      0  A/4. 34244   7.2500   NaN        S  NaN   
1302    male  NaN      0      0        2647   7.2250   NaN        C  NaN   
1303    male  NaN      0      0        2627  14.4583   NaN        C  NaN   
1305  female  NaN      1      0        2665  14.4542   NaN        C  NaN   

      body         home.dest  
15     NaN      New York, NY  
37     NaN   Los Angeles, CA  
40     NaN  Philadelphia, PA  
46     NaN               NaN  
59     NaN      New York, NY  
...    ...               ...  
1293   NaN               NaN  
1297   NaN               NaN  
1302   NaN               NaN  
1303   NaN               NaN  
1305   NaN               NaN  

[263 rows x 14 columns]

In [77]:
# 열 삭제하기 
dataframe.drop('age', axis=1)

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0     female      0      0   24160  211.3375       B5        S    2    NaN   
1       male      1      2  113781  151.5500  C22 C26        S   11    NaN   
2     female      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3       male      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4     female      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
...      ...    ...    ...     ...       ...      ...      ...  ...    ...   
1304  female      1      0    2665   14.4542      NaN        C  NaN  328.0   
1305  female      1      0    2665   14.4542      NaN        C  NaN    NaN   
1306    male      0      0    2656    7.2250      NaN        C  NaN  304.0   
1307    male      0      0    2670    7.2250      NaN        C  NaN    NaN   
1308    male      0      0  315082    7.8750      NaN        S  NaN    NaN   

                            home.dest  
0                        St Louis, MO  
1     Montreal, PQ / Chesterville, ON  
2     Montreal, PQ / Chesterville, ON  
3     Montreal, PQ / Chesterville, ON  
4     Montreal, PQ / Chesterville, ON  
...                               ...  
1304                              NaN  
1305                              NaN  
1306                              NaN  
1307                              NaN  
1308                              NaN  

[1309 rows x 13 columns]

In [78]:
dataframe.drop(['age','sex'], axis=1)

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

      sibsp  parch  ticket      fare    cabin embarked boat   body  \
0         0      0   24160  211.3375       B5        S    2    NaN   
1         1      2  113781  151.5500  C22 C26        S   11    NaN   
2         1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3         1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4         1      2  113781  151.5500  C22 C26        S  NaN    NaN   
...     ...    ...     ...       ...      ...      ...  ...    ...   
1304      1      0    2665   14.4542      NaN        C  NaN  328.0   
1305      1      0    2665   14.4542      NaN        C  NaN    NaN   
1306      0      0    2656    7.2250      NaN        C  NaN  304.0   
1307      0      0    2670    7.2250      NaN        C  NaN    NaN   
1308      0      0  315082    7.8750      NaN        S  NaN    NaN   

                            home.dest  
0                        St Louis, MO  
1     Montreal, PQ / Chesterville, ON  
2     Montreal, PQ / Chesterville, ON  
3     Montreal, PQ / Chesterville, ON  
4     Montreal, PQ / Chesterville, ON  
...                               ...  
1304                              NaN  
1305                              NaN  
1306                              NaN  
1307                              NaN  
1308                              NaN  

[1309 rows x 12 columns]

In [79]:
# 행 삭제 
dataframe[dataframe['sex'] != 'male']

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
2          1         0                     Allison, Miss. Helen Loraine   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
6          1         1                Andrews, Miss. Kornelia Theodosia   
8          1         1    Appleton, Mrs. Edward Dale (Charlotte Lamson)   
...      ...       ...                                              ...   
1286       3         1  Whabee, Mrs. George Joseph (Shawneene Abi-Saab)   
1290       3         1                 Wilkes, Mrs. James (Ellen Needs)   
1300       3         1          Yasbeck, Mrs. Antoni (Selini Alexander)   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   

         sex   age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0      0      0   24160  211.3375       B5        S    2   
2     female   2.0      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0      1      2  113781  151.5500  C22 C26        S  NaN   
6     female  63.0      1      0   13502   77.9583       D7        S   10   
8     female  53.0      2      0   11769   51.4792     C101        S    D   
...      ...   ...    ...    ...     ...       ...      ...      ...  ...   
1286  female  38.0      0      0    2688    7.2292      NaN        C    C   
1290  female  47.0      1      0  363272    7.0000      NaN        S  NaN   
1300  female  15.0      1      0    2659   14.4542      NaN        C  NaN   
1304  female  14.5      1      0    2665   14.4542      NaN        C  NaN   
1305  female   NaN      1      0    2665   14.4542      NaN        C  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
2       NaN  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
6       NaN                       Hudson, NY  
8       NaN              Bayside, Queens, NY  
...     ...                              ...  
1286    NaN                              NaN  
1290    NaN                              NaN  
1300    NaN                              NaN  
1304  328.0                              NaN  
1305    NaN                              NaN  

[466 rows x 14 columns]

In [80]:
dataframe[dataframe['name'] != 'Allison, Miss Helen Loraine']

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN   
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1309 rows x 14 columns]

In [81]:
dataframe[dataframe.index != 0]

pclass  survived                                             name  \
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
5          1         1                              Anderson, Mr. Harry   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN   
5       male  48.0000      0      0   19952   26.5500      E12        S    3   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN   
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
5       NaN                     New York, NY  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1308 rows x 14 columns]

In [82]:
# 중복된 행 삭제 
dataframe.drop_duplicates()

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN   
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1309 rows x 14 columns]

In [83]:
# Show number of rows
print("Number Of Rows In The Original DataFrame: ", len(dataframe))
print("Number Of Rows After Deduping: ", len(dataframe.drop_duplicates()))

Number Of Rows In The Original DataFrame:  1309
Number Of Rows After Deduping:  1309


In [84]:
# 특정 열에서의 중복된 값 제거하기 
dataframe.drop_duplicates(subset=['sex'])

pclass  survived                            name     sex      age  sibsp  \
0       1         1   Allen, Miss. Elisabeth Walton  female  29.0000      0   
1       1         1  Allison, Master. Hudson Trevor    male   0.9167      1   

   parch  ticket      fare    cabin embarked boat  body  \
0      0   24160  211.3375       B5        S    2   NaN   
1      2  113781  151.5500  C22 C26        S   11   NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON

In [85]:
# drop_duplicates의 기본은 처음 나오는 값이나 
# keep으로 옵션을 주어 마지막값을 출력 
dataframe.drop_duplicates(subset=['sex'], keep='last')

pclass  survived                   name     sex   age  sibsp  parch  \
1305       3         0  Zabour, Miss. Thamine  female   NaN      1      0   
1308       3         0     Zimmerman, Mr. Leo    male  29.0      0      0   

      ticket     fare cabin embarked boat  body home.dest  
1305    2665  14.4542   NaN        C  NaN   NaN       NaN  
1308  315082   7.8750   NaN        S  NaN   NaN       NaN

In [86]:
# pclass에서 중복된 값 제거하기 
dataframe.drop_duplicates(subset=['pclass'])

pclass  survived                           name     sex   age  sibsp  \
0         1         1  Allen, Miss. Elisabeth Walton  female  29.0      0   
323       2         0            Abelson, Mr. Samuel    male  30.0      1   
600       3         0            Abbing, Mr. Anthony    male  42.0      0   

     parch     ticket      fare cabin embarked boat  body            home.dest  
0        0      24160  211.3375    B5        S    2   NaN         St Louis, MO  
323      0  P/PP 3381   24.0000   NaN        C  NaN   NaN  Russia New York, NY  
600      0  C.A. 5547    7.5500   NaN        S  NaN   NaN                  NaN

In [87]:
# groupby 
dataframe.groupby('sex').mean()

pclass  survived        age     sibsp     parch       fare  \
sex                                                                    
female  2.154506  0.727468  28.687071  0.652361  0.633047  46.198097   
male    2.372479  0.190985  30.585233  0.413998  0.247924  26.154601   

             body  
sex                
female  166.62500  
male    160.39823

In [89]:
# 생존 여부로 그룹핑하고 이름의 개수 세기
dataframe.groupby('survived')['name'].count()

survived
0    809
1    500
Name: name, dtype: int64

In [90]:
# 성별, 생존여부로 그룹핑하고 각 부문의 나이 평균 구하기 
dataframe.groupby(['sex','survived'])['age'].mean()

sex     survived
female  0           25.255208
        1           29.815354
male    0           31.516412
        1           26.977778
Name: age, dtype: float64

In [91]:
# 시간에 따른 행 그룹핑 
import pandas as pd
import numpy as np

time_index = pd.date_range('06/06/2017', periods = 100000, freq = '30S')

dataframe = pd.DataFrame(index=time_index)
dataframe

Empty DataFrame
Columns: []
Index: [2017-06-06 00:00:00, 2017-06-06 00:00:30, 2017-06-06 00:01:00, 2017-06-06 00:01:30, 2017-06-06 00:02:00, 2017-06-06 00:02:30, 2017-06-06 00:03:00, 2017-06-06 00:03:30, 2017-06-06 00:04:00, 2017-06-06 00:04:30, 2017-06-06 00:05:00, 2017-06-06 00:05:30, 2017-06-06 00:06:00, 2017-06-06 00:06:30, 2017-06-06 00:07:00, 2017-06-06 00:07:30, 2017-06-06 00:08:00, 2017-06-06 00:08:30, 2017-06-06 00:09:00, 2017-06-06 00:09:30, 2017-06-06 00:10:00, 2017-06-06 00:10:30, 2017-06-06 00:11:00, 2017-06-06 00:11:30, 2017-06-06 00:12:00, 2017-06-06 00:12:30, 2017-06-06 00:13:00, 2017-06-06 00:13:30, 2017-06-06 00:14:00, 2017-06-06 00:14:30, 2017-06-06 00:15:00, 2017-06-06 00:15:30, 2017-06-06 00:16:00, 2017-06-06 00:16:30, 2017-06-06 00:17:00, 2017-06-06 00:17:30, 2017-06-06 00:18:00, 2017-06-06 00:18:30, 2017-06-06 00:19:00, 2017-06-06 00:19:30, 2017-06-06 00:20:00, 2017-06-06 00:20:30, 2017-06-06 00:21:00, 2017-06-06 00:21:30, 2017-06-06 00:22:00, 2017-06-06 00:22:30, 2017-06-06 00:23:00, 2017-06-06 00:23:30, 2017-06-06 00:24:00, 2017-06-06 00:24:30, 2017-06-06 00:25:00, 2017-06-06 00:25:30, 2017-06-06 00:26:00, 2017-06-06 00:26:30, 2017-06-06 00:27:00, 2017-06-06 00:27:30, 2017-06-06 00:28:00, 2017-06-06 00:28:30, 2017-06-06 00:29:00, 2017-06-06 00:29:30, 2017-06-06 00:30:00, 2017-06-06 00:30:30, 2017-06-06 00:31:00, 2017-06-06 00:31:30, 2017-06-06 00:32:00, 2017-06-06 00:32:30, 2017-06-06 00:33:00, 2017-06-06 00:33:30, 2017-06-06 00:34:00, 2017-06-06 00:34:30, 2017-06-06 00:35:00, 2017-06-06 00:35:30, 2017-06-06 00:36:00, 2017-06-06 00:36:30, 2017-06-06 00:37:00, 2017-06-06 00:37:30, 2017-06-06 00:38:00, 2017-06-06 00:38:30, 2017-06-06 00:39:00, 2017-06-06 00:39:30, 2017-06-06 00:40:00, 2017-06-06 00:40:30, 2017-06-06 00:41:00, 2017-06-06 00:41:30, 2017-06-06 00:42:00, 2017-06-06 00:42:30, 2017-06-06 00:43:00, 2017-06-06 00:43:30, 2017-06-06 00:44:00, 2017-06-06 00:44:30, 2017-06-06 00:45:00, 2017-06-06 00:45:30, 2017-06-06 00:46:00, 2017-06-06 00:46:30, 2017-06-06 00:47:00, 2017-06-06 00:47:30, 2017-06-06 00:48:00, 2017-06-06 00:48:30, 2017-06-06 00:49:00, 2017-06-06 00:49:30, ...]

[100000 rows x 0 columns]

In [93]:
dataframe['Sale_Amount'] = np.random.randint(1, 10, 100000)
dataframe['Sale_Amount']

2017-06-06 00:00:00    7
2017-06-06 00:00:30    3
2017-06-06 00:01:00    5
2017-06-06 00:01:30    1
2017-06-06 00:02:00    1
                      ..
2017-07-10 17:17:30    2
2017-07-10 17:18:00    3
2017-07-10 17:18:30    1
2017-07-10 17:19:00    9
2017-07-10 17:19:30    5
Freq: 30S, Name: Sale_Amount, Length: 100000, dtype: int32

In [95]:
dataframe.resample('W').sum()

Sale_Amount
2017-06-11        86205
2017-06-18       101385
2017-06-25       101012
2017-07-02       100787
2017-07-09       101205
2017-07-16        10320

In [96]:
# 2주 단위로 그룹화, 평균 계산 
dataframe.resample('2W').mean()

Sale_Amount
2017-06-11     4.988715
2017-06-25     5.019767
2017-07-09     5.009722
2017-07-23     4.961538

In [97]:
# 한달 단위로 그룹화, 행의 개수 세기
dataframe.resample('M').count()

Sale_Amount
2017-06-30        72000
2017-07-31        28000

In [98]:
# Rescale

import numpy as np 
from sklearn import preprocessing

In [99]:
feature = np.array([[-500.5], 
                    [-100.1], 
                    [0],
                    [100.1],
                    [900.9]])

In [101]:
# scaler 생성 
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))

In [102]:
# scale feature 
scaled_feature = minmax_scale.fit_transform(feature)

In [103]:
# show feature
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [104]:
# 표준화하기 (standardizing)
x = np.array([[-1000.5], 
              [-200.1], 
              [100.5],
              [600.6],
              [9000.9]])

In [108]:
scaler = preprocessing.StandardScaler()

StandardScaler()

In [106]:
# 변환
standardized = scaler.fit_transform(x)

In [109]:
standardized

array([[-0.73249562],
       [-0.51541407],
       [-0.43388645],
       [-0.29825116],
       [ 1.9800473 ]])

In [110]:
# 표준화의 효과 
print("Mean: ", round(standardized.mean()))
print("Standard deviation: ", standardized.std())

Mean:  0
Standard deviation:  1.0


In [111]:
# rovustScaler
robust_scaler = preprocessing.RobustScaler()

In [112]:
robust_scaler.fit_transform(x)

array([[-1.37504683],
       [-0.37542151],
       [ 0.        ],
       [ 0.62457849],
       [11.1157737 ]])

In [113]:
# 이상치 찾기

import numpy as np 
from sklearn.covariance import EllipticEnvelope
from sklearn.datasets import make_blobs

In [114]:
# 연습용 데이터 만들기 
features, _ = make_blobs(n_samples = 10, 
                        n_features = 2,
                        centers = 1, 
                        random_state = 1)

In [115]:
features[0,0] = 10000
features[0,1] = 10000

In [127]:
outlier_detector = EllipticEnvelope(contamination = .1)

In [128]:
outlier_detector.fit(features)

EllipticEnvelope()

In [129]:
outlier_detector.predict(features)

array([-1,  1,  1,  1,  1,  1,  1,  1,  1,  1])