# Pytorch
 - Define-by-Run

# Pytorch Packages

 - **torch**
 - torch.autograd
 - torch.nn
 - torch.optim
 - torch.multiprocessing
 - torch.utils
 - torch.legact

# Pytorch Tensor Basic Usage

- Create Tensor
- Indexing, Joining, Slicing
- Initialization
- Math Operations

## 1. Create Tensor

### 1) random numbers

In [2]:
!pip install torch

In [3]:
from __future__ import print_function
import torch

In [4]:
# torch.rand(size)
# 0~1 사이의 연속균등분포에서 값을 뽑아 5x3 텐서를 생성합니다. ~U(0,1)
x = torch.rand(2,3)
x

tensor([[0.0294, 0.0193, 0.8448],
        [0.3380, 0.3001, 0.6968]])

In [5]:
# torch.randn(size)
# randn의 경우 평균은 0, 표준편차는 1인 정규분포에서 값을 가져옵니다. ~z(0,1)
x = torch.randn(2,3)
x

tensor([[ 1.1305,  1.6440,  0.4006],
        [-0.7939,  0.0780,  0.7336]])

In [6]:
# torch.randperm(n)
# 0부터 n-1까지 1씩 늘어나며 값을 랜덤으로 정렬합니다.
x = torch.randperm(5)
x

tensor([4, 1, 0, 2, 3])

### 2) empty, zeros, ones, arange, max

In [8]:
# torch.empty(size)
# 원하는 크기의 아주 작은 값을 가진 텐서를 생성합니다. dtype은 input에 따라 결정됩니다.
x = torch.empty(2,3)
x[1]

tensor([ 8.4218e-43, -1.6204e-01,  8.4218e-43])

In [9]:
x.size()

torch.Size([2, 3])

In [15]:
# torch.zeros(size)
# 원하는 크기의 0 값을 가진 텐서를 생성합니다.
x = torch.zeros(2,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [14]:
# torch.ones(size)
# 원하는 크기의 1의 값을 가진 텐서를 생성합니다.
x = torch.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
# torch.arange(start,end,step=1)
# start값부터 end값 전까지 step만큼 더하며 텐서를 생성합니다.
x = torch.arange(0,3,step=0.5)
x

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])

In [17]:
x.size()

torch.Size([6])

In [23]:
# torch.max(input, dim, keepdim=False, out=None) -> (Tensor, LongTensor)
# tensor의 최대값을 산출합니다.

x = torch.rand(4,8)
print(x)

tensor([[0.5140, 0.3764, 0.2619, 0.4742, 0.7964, 0.1946, 0.6289, 0.0319],
        [0.7108, 0.8100, 0.9615, 0.0827, 0.2949, 0.4927, 0.0748, 0.4178],
        [0.3479, 0.5627, 0.1488, 0.6474, 0.7576, 0.7993, 0.7427, 0.7649],
        [0.3331, 0.5481, 0.7358, 0.5094, 0.8280, 0.1086, 0.4960, 0.5295]])


In [24]:
# 최대값을 출력합니다.
print(torch.max(x))

tensor(0.9615)


In [25]:
# 해당 차원에서 최대값과 그 위치를 출력합니다.
print(torch.max(x,0))
# column 별 max값 추출. indices는 row 위치 

torch.return_types.max(
values=tensor([0.7108, 0.8100, 0.9615, 0.6474, 0.8280, 0.7993, 0.7427, 0.7649]),
indices=tensor([1, 1, 1, 2, 3, 2, 2, 2]))


In [31]:
# 위아래 결과 같음
a = torch.max(x, 0)
print(a)

torch.return_types.max(
values=tensor([0.7108, 0.8100, 0.9615, 0.6474, 0.8280, 0.7993, 0.7427, 0.7649]),
indices=tensor([1, 1, 1, 2, 3, 2, 2, 2]))


In [32]:
print(a[0].shape)

torch.Size([8])


In [33]:
print(torch.max(x,0)[1])
print(x.size(), torch.max(x,0)[1].size())

tensor([1, 1, 1, 2, 3, 2, 2, 2])
torch.Size([4, 8]) torch.Size([8])


In [34]:
# 위치를 출력합니다.
print(torch.max(x,1)[1])
print(x.size(), torch.max(x,1)[1].size())

tensor([4, 2, 5, 4])
torch.Size([4, 8]) torch.Size([4])


### 3) Tensor Data Type

| Data type               | dtype                                         | Tensor types                 |
|:-------------------------|:-----------------------------------------------|:------------------------------|
| 32-bit floating point   | ``` torch.float32 ``` or ``` torch.float ```  | ``` torch.*.FloatTensor ```  |
| 64-bit floating point   | ``` torch.float64 ``` or ``` torch.double ``` | ``` torch.*.DoubleTensor ``` |
| 16-bit floating point   | ``` torch.float16 ``` or ``` torch.half ```   | ``` torch.*.HalfTensor ```   |
| 16-bit integer (signed) | ``` torch.int16 ``` or ``` torch.short ```    | ``` torch.*.ShortTensor ```  |
| 32-bit integer (signed) | ``` torch.int32 ``` or ``` torch.int ```      | ``` torch.*.IntTensor ```    |
| 64-bit integer (signed) | ``` torch.int64 ``` or ``` torch.long ```     | ``` torch.*.LongTensor ```   |

In [36]:
# torch.empty(size, dtype=)
# torch.zeros(size, dtype=)
# torch.arange(start,end,dtype=)

# torch에서 지원하는 다양한 data type을 옵션으로 지정할 수 있습니다.

x = torch.empty(2,3, dtype=torch.float)
y = torch.zeros(2,3, dtype = torch.long)
y2 = torch.zeros(2,3, dtype=torch.float)
z = torch.arange(0,3,step=0.5,dtype=torch.double)

print(x)
print(y)
print(y2)
print(z)

tensor([[0.0000e+00, 0.0000e+00, 1.8754e+28],
        [6.3455e-10, 5.3697e-05, 1.2971e-11]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000], dtype=torch.float64)


In [37]:
# torch.tensor(size or list, dtype = torch.floattensor) 
# 원하는 텐서를 바로 생성합니다.
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [38]:
# torch.FloatTensor(size or list)
x = torch.FloatTensor(2,3) # random 한 값 출력
print(x)
x = torch.FloatTensor([2,3]) # [2, 3] 지정 값 출력 
print(x)

tensor([[0.9600, 0.7064, 0.6475],
        [0.2025, 0.9266, 0.7424]])
tensor([2., 3.])


In [39]:
# tensor.type_as(tensor_type)
# tensor 형 변환
x = x.type_as(torch.IntTensor())
x

tensor([2, 3], dtype=torch.int32)

### 4) Tensor Size

In [43]:
# tensor.size()

x = torch.FloatTensor(10,12,3,3)

print(x.size()[:]) # [:] 없어도 결과는 같다 
print(x.size()[0]) # 가로 길이, 세로 길이 등등 알기 위해 쓰인다 

torch.Size([10, 12, 3, 3])
10


In [44]:
x = x.new_ones(5,3, dtype=torch.double) #5,3 차원의 새로운 텐서를 생성합니다.
print(x)

x = torch.randn_like(x,dtype=torch.float) # 같은 size에서 랜덤한 숫자로 채워진 텐서를 생성합니다.
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.0833, -0.1329,  1.0660],
        [-1.3159,  1.1024, -0.1885],
        [-0.1938,  0.8811, -0.4967],
        [ 0.1152, -0.3039, -0.4556],
        [-1.2618,  0.2037,  1.0332]])


## 2. Math Operations

### 1) add, mul, div

In [45]:
# torch.add()
# 텐서의 값끼리 더합니다.

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
add = torch.add(x1, x2)

x1,x2,add,x1+x2,x1-x2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]),
 tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [49]:
#차원이 다르더라도 안쪽 차원만 같으면 연산이 가능합니다.

x = torch.rand(1,5,3)
y = torch.rand(5,3)
x, y, torch.add(x,y)

(tensor([[[0.1137, 0.9045, 0.0823],
          [0.4118, 0.5081, 0.0862],
          [0.2932, 0.9206, 0.0041],
          [0.1361, 0.2703, 0.6690],
          [0.5706, 0.5599, 0.3617]]]),
 tensor([[0.1278, 0.2187, 0.2637],
         [0.3606, 0.9108, 0.7530],
         [0.2316, 0.2003, 0.6660],
         [0.0422, 0.6132, 0.8950],
         [0.2869, 0.6893, 0.6875]]),
 tensor([[[0.2415, 1.1231, 0.3460],
          [0.7724, 1.4189, 0.8392],
          [0.5248, 1.1209, 0.6701],
          [0.1783, 0.8835, 1.5641],
          [0.8575, 1.2492, 1.0492]]]))

In [50]:
# torch.add 말고 add_의 경우에는 이러한 연산 기능이 지원되지 않습니다. 따라서 먼저 x를 같은 차원으로 바꿔줍니다.

x = torch.rand(5,3)
y.add_(x)
print(y)

tensor([[0.5330, 0.9956, 0.5237],
        [1.1054, 1.4499, 1.6712],
        [0.5800, 0.5580, 1.1599],
        [0.8262, 0.7039, 0.9404],
        [0.9060, 1.0739, 0.9583]])


In [53]:
# x 텐서의 2열을 불러옵니다. numpy 연산이 지원됩니다.

print(x)
print(x.shape)
print(x[:,1])
print(x[:,1].shape)

tensor([[0.4052, 0.7769, 0.2599],
        [0.7448, 0.5391, 0.9182],
        [0.3484, 0.3578, 0.4939],
        [0.7840, 0.0908, 0.0454],
        [0.6191, 0.3846, 0.2709]])
torch.Size([5, 3])
tensor([0.7769, 0.5391, 0.3578, 0.0908, 0.3846])
torch.Size([5])


In [52]:
# torch.mul()
# hadamard product, mxn, mxn 행렬 2개를 곱합니다. 덧셈에 대해 분배법칙을 따릅니다.

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.mul(x1,x2)

x1.size(), x2.size(), x3.size(), x1, x2, x3

(torch.Size([2, 3]),
 torch.Size([2, 3]),
 torch.Size([2, 3]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[ 1.,  4.,  9.],
         [16., 25., 36.]]))

In [54]:
# torch.mul()

x1 = torch.FloatTensor([[1,2,3,],[4,5,6]])
x2 = x1*10

x2

tensor([[10., 20., 30.],
        [40., 50., 60.]])

In [55]:
# torch.div()

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.div(x1,x2)

x3

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [56]:
# torch.div()

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])

x1/5

tensor([[0.2000, 0.4000, 0.6000],
        [0.8000, 1.0000, 1.2000]])

### 2) pow, exp, log

In [57]:
# torch.pow(input,exponent)

x1 = torch.rand(3,4)

print(x1)
print(torch.pow(x1,2),"\n",x1**2)

tensor([[0.9830, 0.5238, 0.5079, 0.9981],
        [0.7108, 0.4618, 0.8525, 0.4909],
        [0.8537, 0.2480, 0.8144, 0.7370]])
tensor([[0.9664, 0.2744, 0.2579, 0.9962],
        [0.5053, 0.2132, 0.7268, 0.2410],
        [0.7289, 0.0615, 0.6633, 0.5432]]) 
 tensor([[0.9664, 0.2744, 0.2579, 0.9962],
        [0.5053, 0.2132, 0.7268, 0.2410],
        [0.7289, 0.0615, 0.6633, 0.5432]])


In [58]:
# torch.exp(tensor,out=None)

x1 = torch.rand(3,4)

print(x1)
print(torch.exp(x1))

tensor([[0.7594, 0.9099, 0.7447, 0.3418],
        [0.1413, 0.7171, 0.4552, 0.4370],
        [0.6278, 0.1647, 0.2310, 0.4615]])
tensor([[2.1370, 2.4840, 2.1059, 1.4075],
        [1.1517, 2.0484, 1.5765, 1.5481],
        [1.8736, 1.1791, 1.2599, 1.5864]])


In [59]:
# torch.log(input,out=None)

x1 = torch.rand(3,4)

print(x1)
print(torch.log(x1))

tensor([[0.5290, 0.0959, 0.6944, 0.7847],
        [0.8456, 0.0700, 0.4111, 0.2398],
        [0.5042, 0.6945, 0.6600, 0.8695]])
tensor([[-0.6367, -2.3446, -0.3647, -0.2425],
        [-0.1678, -2.6594, -0.8889, -1.4278],
        [-0.6848, -0.3645, -0.4155, -0.1399]])


In [60]:
# torch.mm(matrix1, matrix2)

x1 = torch.rand(3,4)
x2 = torch.rand(4,5)

torch.mm(x1,x2)

tensor([[0.9718, 0.6305, 0.7839, 1.0281, 0.9934],
        [1.3697, 1.4036, 1.6804, 1.5064, 2.2176],
        [0.7195, 0.6241, 0.6631, 0.7238, 0.9427]])

In [61]:
# torch.bmm(batch_matrix1, batch_matrix2)

x1 = torch.rand(10,3,4)
x2 = torch.rand(10,4,5)

torch.bmm(x1,x2).size()

torch.Size([10, 3, 5])

![img](https://github.com/shwksl101/Pytorch-A-to-Z/blob/master/img/innerproduct.PNG?raw=true)

In [62]:
# torch.dot(tensor1, tensor2)

torch.dot(torch.tensor([2,3]), torch.tensor([2,1]))

tensor(7)

In [63]:
# torch.t(matrix)
# tranpose

x1 = torch.rand(3,4)
print(x1.size(), x1.t().size()) # t: transpose 

torch.Size([3, 4]) torch.Size([4, 3])


In [64]:
# torch.transpose(input,dim0,dim1)

x1 = torch.rand(10,3,4)
x1.size(), torch.transpose(x1,1,2).size(), x1.transpose(1,2).size() #contiguous

(torch.Size([10, 3, 4]), torch.Size([10, 4, 3]), torch.Size([10, 4, 3]))

In [65]:
# torch.eig(a,eigenvectors=Flase)
# eigen_value, eigen_vector

x1 = torch.rand(2,2)

print(x1,"\n",torch.eig(x1,True))

tensor([[0.7198, 0.3332],
        [0.9964, 0.2153]]) 
 torch.return_types.eig(
eigenvalues=tensor([[ 1.0966,  0.0000],
        [-0.1615,  0.0000]]),
eigenvectors=tensor([[ 0.6625, -0.3537],
        [ 0.7491,  0.9354]]))


<ipython-input-65-7f5b7b16cc56>:6: UserWarning: torch.eig is deprecated in favor of torch.linalg.eig and will be removed in a future PyTorch release.
torch.linalg.eig returns complex tensors of dtype cfloat or cdouble rather than real tensors mimicking complex tensors.
L, _ = torch.eig(A)
should be replaced with
L_complex = torch.linalg.eigvals(A)
and
L, V = torch.eig(A, eigenvectors=True)
should be replaced with
L_complex, V_complex = torch.linalg.eig(A) (Triggered internally at  ..\aten\src\ATen\native\BatchLinearAlgebra.cpp:2894.)
  print(x1,"\n",torch.eig(x1,True))


### 3) view, item

In [67]:
# view()

x = torch.randn(4,4)
y = x.view(16) # 재배치 
z = x.view(-1,8) # -1의 경우 다른 차원들로 유추, 이 경우에는 2로 유추한다(16 // 8)
print(x.size())
print(y.size(),y)
print(z.size(),z)

torch.Size([4, 4])
torch.Size([16]) tensor([-0.5981,  0.8221, -1.5400,  0.7850,  0.0891,  0.1336,  0.4833,  0.6645,
        -2.3763,  0.4934, -0.1077, -1.1779, -0.3350,  1.4465, -0.5613,  1.4165])
torch.Size([2, 8]) tensor([[-0.5981,  0.8221, -1.5400,  0.7850,  0.0891,  0.1336,  0.4833,  0.6645],
        [-2.3763,  0.4934, -0.1077, -1.1779, -0.3350,  1.4465, -0.5613,  1.4165]])


In [68]:
# item()

x = torch.randn(1)
print(x)
print(x.item()) # 앞에 붙는 tensor를 표시하지 않음 

tensor([-0.3183])
-0.3183193504810333


- 더 많은 연산은 다음의 링크에서 참고하세요 https://pytorch.org/docs/stable/torch.html

## 3. Tensor to Numpy, Numpy to Tensor

In [69]:
import numpy as np

In [70]:
a = torch.ones(5) # 1로 채워진 텐서를 생성합니다.
print(a)

tensor([1., 1., 1., 1., 1.])


In [71]:
# tensor.numpy()

b = a.numpy() # ','가 사라진다 
print(b)

[1. 1. 1. 1. 1.]


In [72]:
# torch.from_numpy(ndarray)

a = np.ones(5) #a와 b는 연동됩니다.
b = torch.from_numpy(a)

np.add(a,1,out=a)

print(a)
print(b) #chartensor를 제외한 모든 tensor는 numpy로의 변환을 지원합니다.

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## 4. Tensor on GPU

In [77]:
x= torch.FloatTensor([[1,2,3],[4,5,6]])

if torch.cuda.is_available():
    x_cuda = x.cuda()
else:
    x_cuda = x.cpu()
    
print(x_cuda)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [78]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    
    y = torch.ones_like(x,device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu")) #.to 기능을 tensor를 GPU로 연산할 수 있습니다
    print(z.to("cuda"))

## 5. Indexing, Slicing, Joining

### 1) Indexing

In [81]:
torch.cuda.is_available()

False

In [75]:
# tensor.index_select(input,dim,index)

x = torch.rand(4,3)
out = torch.index_select(x,0,torch.LongTensor([0,3]))
# index는 꼭 Longtensor로 입력해야 합니다.

print(x.size(), out.size())
print(x, "\n", out)

torch.Size([4, 3]) torch.Size([2, 3])
tensor([[0.9143, 0.9597, 0.6971],
        [0.1201, 0.7379, 0.8873],
        [0.5797, 0.9752, 0.9594],
        [0.1918, 0.0718, 0.2254]]) 
 tensor([[0.9143, 0.9597, 0.6971],
        [0.1918, 0.0718, 0.2254]])


In [76]:
print(x.size(),'\n', x)
print(x[:,0].size(),x[:,0])
print(x[0,:].size(),x[0,:])
print(x[0:2,0:2].size(),'\n', x[0:2,0:2])

torch.Size([4, 3]) 
 tensor([[0.9143, 0.9597, 0.6971],
        [0.1201, 0.7379, 0.8873],
        [0.5797, 0.9752, 0.9594],
        [0.1918, 0.0718, 0.2254]])
torch.Size([4]) tensor([0.9143, 0.1201, 0.5797, 0.1918])
torch.Size([3]) tensor([0.9143, 0.9597, 0.6971])
torch.Size([2, 2]) 
 tensor([[0.9143, 0.9597],
        [0.1201, 0.7379]])


### 2) Joining

In [83]:
# torch.cat(seq, dim=0)
# dim을 기준으로 tensor를 합칩니다.
# dim = 0은 행, dim = 1은 열 기준입니다.

x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])
y = torch.FloatTensor([[7,8,9],
                       [10,11,12]])
z1 = torch.cat([x,y],dim = 0) # 위아래로 붙임
z2 = torch.cat([x,y],dim = 1) # 양옆으로 붙임 

print(x, x.shape)
print(y, y.shape)
print(z1, z1.shape)
print(z2, z2.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]]) torch.Size([2, 3])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]]) torch.Size([2, 3])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]]) torch.Size([4, 3])
tensor([[ 1.,  2.,  3.,  7.,  8.,  9.],
        [ 4.,  5.,  6., 10., 11., 12.]]) torch.Size([2, 6])


In [87]:
# torch.stack(sequence,dim=0)
# dim을 기준으로 쌓습니다.

x = torch.FloatTensor([1,2,3])
x_stack = torch.stack([x,x],dim=0)
x_stack2 = torch.stack([x,x],dim=1)

print(x_stack,"\n",x_stack2)

print(x.shape)
print('='*10)
print(x_stack, x_stack.shape)
print(x_stack2, x_stack2.shape)

tensor([[1., 2., 3.],
        [1., 2., 3.]]) 
 tensor([[1., 1.],
        [2., 2.],
        [3., 3.]])
torch.Size([3])
tensor([[1., 2., 3.],
        [1., 2., 3.]]) torch.Size([2, 3])
tensor([[1., 1.],
        [2., 2.],
        [3., 3.]]) torch.Size([3, 2])


### 3) Slicing

In [89]:
# torch.chunk(tensor, chunks, dim=0)
# tensor를 chunk 단위로 쪼갭니다. chunk 개수 만큼 생성합니다.

x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])
y = torch.FloatTensor([[7,8,9],
                       [10,11,12]])
z1 = torch.cat([x,y],dim = 0)

x_1, x_2 = torch.chunk(z1,2,dim=0)
y_1, y_2, y_3 = torch.chunk(z1,3,dim=1)

print(z1)
print('='*10)
print(x_1)
print(x_2)
print('='*10)
print(y_1)
print(y_2)
print(y_3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.],
        [ 4.],
        [ 7.],
        [10.]])
tensor([[ 2.],
        [ 5.],
        [ 8.],
        [11.]])
tensor([[ 3.],
        [ 6.],
        [ 9.],
        [12.]])


In [90]:
# torch.split(tensor,split_size,dim=0) 각 size가 split_size만큼인 것을 생성합니다.

x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])
y = torch.FloatTensor([[7,8,9],
                       [10,11,12]])
z1 = torch.cat([x,y],dim = 0)

x1,x2 = torch.split(z1,2,dim=0)
y1,y2 = torch.split(z1,2,dim=1)

print(z1)
print('='*10)
print(x1)
print(x2)
print('='*10)
print(y1)
print(y2)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])
tensor([[ 3.],
        [ 6.],
        [ 9.],
        [12.]])


### 4) squeezing

In [91]:
# torch.squeeze(input, dim=None)
# 1짜리 차원을 줄입니다.

x1 = torch.FloatTensor(10,1,3,1,4)
x2 = torch.squeeze(x1)

x1.size(), x2.size()

(torch.Size([10, 1, 3, 1, 4]), torch.Size([10, 3, 4]))

In [92]:
# torch.unsqueeze(input,dim=None)
# 1짜리 차원을 더합니다.

x1 = torch.FloatTensor(10,3,4)
x2 = torch.unsqueeze(x1,dim=0)

x.size(), x2.size()

(torch.Size([2, 3]), torch.Size([1, 10, 3, 4]))

## 6. Initialization

In [93]:
import torch.nn.init as init

x1 = init.uniform_(torch.FloatTensor(3,4),a=0,b=9) 
x2 = init.normal_(torch.FloatTensor(3,4),std=0.2)
x3 = init.constant_(torch.FloatTensor(3,4),3.1415)

x1,x2,x3

(tensor([[1.5693, 5.5568, 1.7634, 4.1538],
         [3.7740, 8.9895, 5.5636, 0.7853],
         [8.0119, 6.1980, 4.1393, 6.9165]]),
 tensor([[-0.1933,  0.0329, -0.0046, -0.1756],
         [-0.1203,  0.0747,  0.2284,  0.0051],
         [-0.0972,  0.2635,  0.1624,  0.4334]]),
 tensor([[3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415]]))