In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/bike-sharing-demand/sampleSubmission.csv
/kaggle/input/bike-sharing-demand/train.csv
/kaggle/input/bike-sharing-demand/test.csv


In [2]:
sample_submission = pd.read_csv('/kaggle/input/bike-sharing-demand/sampleSubmission.csv')
sample_submission

datetime  count
0     2011-01-20 00:00:00      0
1     2011-01-20 01:00:00      0
2     2011-01-20 02:00:00      0
3     2011-01-20 03:00:00      0
4     2011-01-20 04:00:00      0
...                   ...    ...
6488  2012-12-31 19:00:00      0
6489  2012-12-31 20:00:00      0
6490  2012-12-31 21:00:00      0
6491  2012-12-31 22:00:00      0
6492  2012-12-31 23:00:00      0

[6493 rows x 2 columns]

In [3]:
train_df = pd.read_csv('/kaggle/input/bike-sharing-demand/train.csv')
test_df = pd.read_csv('/kaggle/input/bike-sharing-demand/test.csv')

In [4]:
train_df

datetime  season  holiday  workingday  weather   temp  \
0      2011-01-01 00:00:00       1        0           0        1   9.84   
1      2011-01-01 01:00:00       1        0           0        1   9.02   
2      2011-01-01 02:00:00       1        0           0        1   9.02   
3      2011-01-01 03:00:00       1        0           0        1   9.84   
4      2011-01-01 04:00:00       1        0           0        1   9.84   
...                    ...     ...      ...         ...      ...    ...   
10881  2012-12-19 19:00:00       4        0           1        1  15.58   
10882  2012-12-19 20:00:00       4        0           1        1  14.76   
10883  2012-12-19 21:00:00       4        0           1        1  13.94   
10884  2012-12-19 22:00:00       4        0           1        1  13.94   
10885  2012-12-19 23:00:00       4        0           1        1  13.12   

        atemp  humidity  windspeed  casual  registered  count  
0      14.395        81     0.0000       3          13     16  
1      13.635        80     0.0000       8          32     40  
2      13.635        80     0.0000       5          27     32  
3      14.395        75     0.0000       3          10     13  
4      14.395        75     0.0000       0           1      1  
...       ...       ...        ...     ...         ...    ...  
10881  19.695        50    26.0027       7         329    336  
10882  17.425        57    15.0013      10         231    241  
10883  15.910        61    15.0013       4         164    168  
10884  17.425        61     6.0032      12         117    129  
10885  16.665        66     8.9981       4          84     88  

[10886 rows x 12 columns]

In [5]:
test_df

datetime  season  holiday  workingday  weather   temp  \
0     2011-01-20 00:00:00       1        0           1        1  10.66   
1     2011-01-20 01:00:00       1        0           1        1  10.66   
2     2011-01-20 02:00:00       1        0           1        1  10.66   
3     2011-01-20 03:00:00       1        0           1        1  10.66   
4     2011-01-20 04:00:00       1        0           1        1  10.66   
...                   ...     ...      ...         ...      ...    ...   
6488  2012-12-31 19:00:00       1        0           1        2  10.66   
6489  2012-12-31 20:00:00       1        0           1        2  10.66   
6490  2012-12-31 21:00:00       1        0           1        1  10.66   
6491  2012-12-31 22:00:00       1        0           1        1  10.66   
6492  2012-12-31 23:00:00       1        0           1        1  10.66   

       atemp  humidity  windspeed  
0     11.365        56    26.0027  
1     13.635        56     0.0000  
2     13.635        56     0.0000  
3     12.880        56    11.0014  
4     12.880        56    11.0014  
...      ...       ...        ...  
6488  12.880        60    11.0014  
6489  12.880        60    11.0014  
6490  12.880        60    11.0014  
6491  13.635        56     8.9981  
6492  13.635        65     8.9981  

[6493 rows x 9 columns]

In [6]:
train_features = train_df.values[:, 1:-3].astype(float)
train_features

array([[ 1.    ,  0.    ,  0.    , ..., 14.395 , 81.    ,  0.    ],
       [ 1.    ,  0.    ,  0.    , ..., 13.635 , 80.    ,  0.    ],
       [ 1.    ,  0.    ,  0.    , ..., 13.635 , 80.    ,  0.    ],
       ...,
       [ 4.    ,  0.    ,  1.    , ..., 15.91  , 61.    , 15.0013],
       [ 4.    ,  0.    ,  1.    , ..., 17.425 , 61.    ,  6.0032],
       [ 4.    ,  0.    ,  1.    , ..., 16.665 , 66.    ,  8.9981]])

In [7]:
test_features = test_df.values[:, 1:].astype(float)
test_features

array([[ 1.    ,  0.    ,  1.    , ..., 11.365 , 56.    , 26.0027],
       [ 1.    ,  0.    ,  1.    , ..., 13.635 , 56.    ,  0.    ],
       [ 1.    ,  0.    ,  1.    , ..., 13.635 , 56.    ,  0.    ],
       ...,
       [ 1.    ,  0.    ,  1.    , ..., 12.88  , 60.    , 11.0014],
       [ 1.    ,  0.    ,  1.    , ..., 13.635 , 56.    ,  8.9981],
       [ 1.    ,  0.    ,  1.    , ..., 13.635 , 65.    ,  8.9981]])

In [8]:
train_features.shape, test_features.shape

((10886, 8), (6493, 8))

In [9]:
mean = train_features.mean(0)
stdev = train_features.std(0)
mean.shape, stdev.shape

((8,), (8,))

In [10]:
mean, stdev

(array([2.50661400e+00, 2.85688040e-02, 6.80874518e-01, 1.41842734e+00,
        2.02308598e+01, 2.36550841e+01, 6.18864597e+01, 1.27993954e+01]),
 array([ 1.11612304,  0.1665912 ,  0.46613776,  0.63380947,  7.79123196,
         8.47421137, 19.24414932,  8.16416232]))

In [11]:
train_features = (train_features - mean) / stdev
train_features

array([[-1.34986372, -0.17149048, -1.46067232, ..., -1.09273697,
         0.99321305, -1.56775367],
       [-1.34986372, -0.17149048, -1.46067232, ..., -1.18242083,
         0.94124921, -1.56775367],
       [-1.34986372, -0.17149048, -1.46067232, ..., -1.18242083,
         0.94124921, -1.56775367],
       ...,
       [ 1.33801198, -0.17149048,  0.68461625, ..., -0.91395927,
        -0.04606385,  0.26970368],
       [ 1.33801198, -0.17149048,  0.68461625, ..., -0.73518157,
        -0.04606385, -0.83244247],
       [ 1.33801198, -0.17149048,  0.68461625, ..., -0.82486544,
         0.21375537, -0.46560752]])

train: (10886, 8), test: (6493, 8) -> difference.shape: (6493, 10886, 8)

In [12]:
test_features = (test_features - mean) / stdev
test_features

array([[-1.34986372, -0.17149048,  0.68461625, ..., -1.45029236,
        -0.30588308,  1.61722711],
       [-1.34986372, -0.17149048,  0.68461625, ..., -1.18242083,
        -0.30588308, -1.56775367],
       [-1.34986372, -0.17149048,  0.68461625, ..., -1.18242083,
        -0.30588308, -1.56775367],
       ...,
       [-1.34986372, -0.17149048,  0.68461625, ..., -1.27151467,
        -0.0980277 , -0.22023024],
       [-1.34986372, -0.17149048,  0.68461625, ..., -1.18242083,
        -0.30588308, -0.46560752],
       [-1.34986372, -0.17149048,  0.68461625, ..., -1.18242083,
         0.16179153, -0.46560752]])

In [13]:
difference = train_features[None, :, :] - test_features[:, None, :]
difference

array([[[ 0.        ,  0.        , -2.14528856, ...,  0.3575554 ,
          1.29909613, -3.18498077],
        [ 0.        ,  0.        , -2.14528856, ...,  0.26787153,
          1.24713229, -3.18498077],
        [ 0.        ,  0.        , -2.14528856, ...,  0.26787153,
          1.24713229, -3.18498077],
        ...,
        [ 2.6878757 ,  0.        ,  0.        , ...,  0.53633309,
          0.25981923, -1.34752343],
        [ 2.6878757 ,  0.        ,  0.        , ...,  0.71511079,
          0.25981923, -2.44966957],
        [ 2.6878757 ,  0.        ,  0.        , ...,  0.62542693,
          0.51963845, -2.08283463]],

       [[ 0.        ,  0.        , -2.14528856, ...,  0.08968386,
          1.29909613,  0.        ],
        [ 0.        ,  0.        , -2.14528856, ...,  0.        ,
          1.24713229,  0.        ],
        [ 0.        ,  0.        , -2.14528856, ...,  0.        ,
          1.24713229,  0.        ],
        ...,
        [ 2.6878757 ,  0.        ,  0.        , ...,  

In [14]:
difference.shape

(6493, 10886, 8)

In [15]:
difference = difference ** 2
difference = difference.mean(-1) # 마지막 행끼리 mean 구하기

In [16]:
difference.shape

(6493, 10886)

In [17]:
prediction_index = difference.argmin(1)
prediction_index, prediction_index.shape

(array([6480,  898,  898, ..., 5539, 5615, 1186]), (6493,))

In [18]:
prediction = train_df['count'].values[prediction_index]
prediction, prediction.shape

(array([108,  63,  63, ...,  71,   5,   3]), (6493,))

In [19]:
new_submission = sample_submission.copy()

In [20]:
new_submission

datetime  count
0     2011-01-20 00:00:00      0
1     2011-01-20 01:00:00      0
2     2011-01-20 02:00:00      0
3     2011-01-20 03:00:00      0
4     2011-01-20 04:00:00      0
...                   ...    ...
6488  2012-12-31 19:00:00      0
6489  2012-12-31 20:00:00      0
6490  2012-12-31 21:00:00      0
6491  2012-12-31 22:00:00      0
6492  2012-12-31 23:00:00      0

[6493 rows x 2 columns]

In [21]:
new_submission['count'] = prediction

In [22]:
new_submission

datetime  count
0     2011-01-20 00:00:00    108
1     2011-01-20 01:00:00     63
2     2011-01-20 02:00:00     63
3     2011-01-20 03:00:00    106
4     2011-01-20 04:00:00    106
...                   ...    ...
6488  2012-12-31 19:00:00     98
6489  2012-12-31 20:00:00     98
6490  2012-12-31 21:00:00     71
6491  2012-12-31 22:00:00      5
6492  2012-12-31 23:00:00      3

[6493 rows x 2 columns]

In [23]:
new_submission.to_csv('submission.csv', index=False)